[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[functions.claim-daily]
verify_jwt = false

[functions.complete-run]
verify_jwt = false

[functions.purchase-upgrade]
verify_jwt = false

[auth]
enabled = true
site_url = "http://localhost:5175"
additional_redirect_urls = ["http://localhost:5175", "http://localhost:5176", "http://localhost:5177", "http://localhost:5178"]

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
redirect_uri = "http://127.0.0.1:54321/auth/v1/callback"
