name: soulblade

services:
  postgres:
    image: postgres:16-alpine
    container_name: soulblade-db
    environment:
      POSTGRES_USER: soulblade
      POSTGRES_PASSWORD: soulblade
      POSTGRES_DB: soulblade_dev
    ports:
      - '5434:5432'
    volumes:
      - soulblade_pgdata:/var/lib/postgresql/data
      - ./prisma/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  soulblade_pgdata:
